### ISSUE TITLE
Could not load the Space: fffiloni/mmpose-estimation

### ISSUE THREAD

**Issue by Source419** [mayuelala/FollowYourPose#17]
Fetching Space from: https://huggingface.co/spaces/fffiloni/mmpose-estimation
Traceback (most recent call last):
  File "/root/miniconda3/envs/env39/lib/python3.9/site-packages/gradio/external.py", line 436, in from_spaces
    config = json.loads(result.group(1))  # type: ignore
AttributeError: 'NoneType' object has no attribute 'group'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/autodl-tmp/FollowYourPose/app.py", line 28, in <module>
    pipe = merge_config_then_run()
  File "/root/autodl-tmp/FollowYourPose/inference_followyourpose.py", line 25, in __init__
    self.mmpose = gr.load(name="spaces/fffiloni/mmpose-estimation")
  File "/root/miniconda3/envs/env39/lib/python3.9/site-packages/gradio/external.py", line 68, in load
    return load_blocks_from_repo(
  File "/root/miniconda3/envs/env39/lib/python3.9/site-packages/gradio/external.py", line 107, in load_blocks_from_repo
    blocks: gradio.Blocks = factory_methods[src](name, api_key, alias, **kwargs)
  File "/root/miniconda3/envs/env39/lib/python3.9/site-packages/gradio/external.py", line 438, in from_spaces
    raise ValueError("Could not load the Space: {}".format(space_name))
ValueError: Could not load the Space: fffiloni/mmpose-estimation

I used to be successful, but today suddenly it's not working. Has anyone had the same problem？

**Comment by sjtuytc** [comment]
Yes, this space is not available now.

**Comment by mayuelala** [comment]
Thank you for attention，we have fix it~， you can try it again

**Comment by Rajathbharadwaj** [comment]
Hey, I'm facing the same issue. Now I saw the space, it shows this
Runtime error
Scheduling failure: not enough hardware capacity

**Comment by treesturn** [comment]
Experiencing this error now as well "ValueError: Could not load the Space: fffiloni/mmpose-estimation" @mayuelala
