### ISSUE TITLE
error colab

### ISSUE THREAD

**Issue by loboere** [mayuelala/FollowYourPose#5]
```
/content/FollowYourPose
/content/FollowYourPose
The following values were not passed to `accelerate launch` and had defaults used instead:
	`--num_processes` was set to a value of `1`
	`--num_machines` was set to a value of `1`
	`--mixed_precision` was set to a value of `'no'`
	`--dynamo_backend` was set to a value of `'no'`
To avoid this warning pass in values for each of the problematic parameters or run `accelerate config`.
A matching Triton is not available, some optimizations will not be enabled.
Error caught was: module 'triton.language' has no attribute 'constexpr'
/usr/local/lib/python3.8/dist-packages/torchvision/transforms/_functional_video.py:6: UserWarning: The 'torchvision.transforms._functional_video' module is deprecated since 0.12 and will be removed in the future. Please use the 'torchvision.transforms.functional' module instead.
  warnings.warn(
/usr/local/lib/python3.8/dist-packages/torchvision/transforms/_transforms_video.py:22: UserWarning: The 'torchvision.transforms._transforms_video' module is deprecated since 0.12 and will be removed in the future. Please use the 'torchvision.transforms' module instead.
  warnings.warn(
Traceback (most recent call last):
  File "txt2video.py", line 28, in <module>
    from followyourpose.pipelines.pipeline_followyourpose import FollowYourPosePipeline
  File "/content/FollowYourPose/followyourpose/pipelines/pipeline_followyourpose.py", line 43, in <module>
    class FollowYourPosePipeline(DiffusionPipeline):
  File "/content/FollowYourPose/followyourpose/pipelines/pipeline_followyourpose.py", line 333, in FollowYourPosePipeline
    **kwargs,
NameError: name 'kwargs' is not defined
Traceback (most recent call last):
  File "/usr/local/bin/accelerate", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.8/dist-packages/accelerate/commands/accelerate_cli.py", line 45, in main
    args.func(args)
  File "/usr/local/lib/python3.8/dist-packages/accelerate/commands/launch.py", line 1097, in launch_command
    simple_launcher(args)
  File "/usr/local/lib/python3.8/dist-packages/accelerate/commands/launch.py", line 552, in simple_launcher
    raise subprocess.CalledProcessError(returncode=process.returncode, cmd=cmd)
subprocess.CalledProcessError: Command '['/usr/bin/python3.8', 'txt2video.py', '--config=configs/pose_sample.yaml', '--skeleton_path=./pose_example/vis_ikun_pose2.mov']' returned non-zero exit status 1.
```

**Comment by wandrzej** [comment]
Got the same error. 
There's a typo in pose_sampe.yaml  - you need to remove the s in line 17

Also the kwargs name error is fixed with adding a missing  comma in pipeline_followyourpose.py, line 332 and removing the one after **kwargs

**Comment by mayuelala** [comment]
Hi, we have fixed this bug, please try it again~
