### ISSUE TITLE
mmpose TypeError: wrapper() got an unexpected keyword argument 'fn_index'

### ISSUE THREAD

**Issue by yaohwang** [mayuelala/FollowYourPose#51]
Traceback (most recent call last):
  File "/FollowYourPose/app.py", line 177, in <module>
    gr.Examples(examples=examples,
  File "/root/miniconda3/envs/python-app/lib/python3.9/site-packages/gradio/helpers.py", line 75, in create_examples
    examples_obj.create()
  File "/root/miniconda3/envs/python-app/lib/python3.9/site-packages/gradio/helpers.py", line 301, in create
    client_utils.synchronize_async(self.cache)
  File "/root/miniconda3/envs/python-app/lib/python3.9/site-packages/gradio_client/utils.py", line 808, in synchronize_async
    return fsspec.asyn.sync(fsspec.asyn.get_loop(), func, *args, **kwargs)  # type: ignore
  File "/root/miniconda3/envs/python-app/lib/python3.9/site-packages/fsspec/asyn.py", line 103, in sync
    raise return_result
  File "/root/miniconda3/envs/python-app/lib/python3.9/site-packages/fsspec/asyn.py", line 56, in _runner
    result[0] = await coro
  File "/root/miniconda3/envs/python-app/lib/python3.9/site-packages/gradio/helpers.py", line 362, in cache
    prediction = await Context.root_block.process_api(
  File "/root/miniconda3/envs/python-app/lib/python3.9/site-packages/gradio/blocks.py", line 1561, in process_api
    result = await self.call_function(
  File "/root/miniconda3/envs/python-app/lib/python3.9/site-packages/gradio/blocks.py", line 1179, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "/root/miniconda3/envs/python-app/lib/python3.9/site-packages/anyio/to_thread.py", line 56, in run_sync
    return await get_async_backend().run_sync_in_worker_thread(
  File "/root/miniconda3/envs/python-app/lib/python3.9/site-packages/anyio/_backends/_asyncio.py", line 2134, in run_sync_in_worker_thread
    return await future
  File "/root/miniconda3/envs/python-app/lib/python3.9/site-packages/anyio/_backends/_asyncio.py", line 851, in run
    result = context.run(func, *args)
  File "/root/miniconda3/envs/python-app/lib/python3.9/site-packages/gradio/utils.py", line 695, in wrapper
    response = f(*args, **kwargs)
  File "/FollowYourPose/inference_followyourpose.py", line 50, in run
    infer_skeleton(self.mmpose, data_path)
  File "/FollowYourPose/inference_mmpose.py", line 97, in infer_skeleton
    mmpose_frame = get_mmpose_filter(mmpose, i)
  File "/FollowYourPose/inference_mmpose.py", line 63, in get_mmpose_filter
    image = mmpose(i, fn_index=0)[1]
  File "/root/miniconda3/envs/python-app/lib/python3.9/site-packages/gradio/events.py", line 74, in __call__
    return self.fn(*args, **kwargs)
TypeError: wrapper() got an unexpected keyword argument 'fn_index'

**Comment by mayuelala** [comment]
maybe the version of mmpose is wrong
